# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: DownloadSecureFile@1
  name: privateKey
  inputs:
    secureFile: 15c9270acc563cb0d3ba82299ef3eb6ddfc87ef69dd0558e9cb2dd6d60ada1d8.key
- script: |
    mkdir -p  $(System.DefaultWorkingDirectory)/trust/private
    cp $(privateKey.secureFilePath)  $(System.DefaultWorkingDirectory)/trust/private
    echo $(System.DefaultWorkingDirectory)/trust/private
    git clone https://github.com/ayushigupta-12/devopsrbapoc

- task: Docker@2
  inputs:
    command: build
    Dockerfile: 'dockerfile1'
    containerRegistry: acr-connection
    repository: demopoc
    tags: |
      latest
    arguments: '--disable-content-trust=false'
- script: |
    az acr login -n acr5000.azurecr.io
    docker trust signer add --key 7cbecf5ebd0b532cd5324fbd92242c36f870a69761ef246c9ad2bce149c29826.key poc acr5000.azurecr.io/demopoc

- task: Docker@0
  inputs: 
    containerregistrytype: Azure Container Registry
    azureSubscription: Azure-Infra-Terraform
    azurecontainerRegistry: acr5000
    action: Push an image
    imageName: acr5000.azurecr.io/demopoc:latest
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: tcspoc123
