# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: DownloadSecureFile@1
  name: certificate
  inputs:
    secureFile: mypoc.crt
- script: |
    mkdir -p  $(DOCKER_CONFIG)/trust/private
    cp $(certificate.secureFilePath)  $(DOCKER_CONFIG)/trust/private
    echo $(DOCKER_CONFIG)/trust/private
    git clone https://github.com/ayushigupta-12/devopsrbapoc

- task: DownloadSecureFile@1
  name: privatekey
  inputs:
    secureFile: mykey.key
- script: |
    cp $(privateKey.secureFilePath)  $(DOCKER_CONFIG)/trust/private
    echo $(DOCKER_CONFIG)/trust/private

- task: Docker@0
  inputs:
    Dockerfile: 'dockerfile1'
    containerRegistryType: Azure Container Registry
    azureSubscription: Azure-Infra-Terraform
    action: "Build an Image"
    azureContainerRegistry: acr5000.azurecr.io
    imageName: demopoc1:latest
#    arguments: '--disable-content-trust=false'
  env:
    DOCKER_CONTENT_TRUST: 1
- script: |
    echo $(System.DefaultWorkingDirectory)
    cd $(DOCKER_CONFIG)/trust/private
    chmod 600 mykey.key
    export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="tcspoc123"
    docker trust key load mykey.key --name tcspoc
    az acr login -n acr5000.azurecr.io
    export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE="tcspoc123"
    export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="tcspoc123"
    docker trust signer add --key mypoc.crt tcspoc acr5000.azurecr.io/demopoc1:latest
    ls
    docker trust key load 042c10894219a41ad36d47dcb95c8e70df49f31d169c02a757eeb9419b02a980.key
    docker trust inspect --pretty acr5000.azurecr.io/demopoc1:latest

- task: Docker@0
  inputs: 
    containerregistrytype: Azure Container Registry
    azureSubscription: Azure-Infra-Terraform
    azurecontainerRegistry: acr5000
    action: Push an image
    imageName: acr5000.azurecr.io/demopoc1:latest
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: tcspoc123
