# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: DownloadSecureFile@1
  name: privateKey
  inputs:
    secureFile: 7cbecf5ebd0b532cd5324fbd92242c36f870a69761ef246c9ad2bce149c29826.key
- script: |
    mkdir -p $(DOCKER_CONFIG)/trust/private
    cp $(privateKey.secureFilePath) $(DOCKER_CONFIG)/trust/private

- task: Docker@0
  inputs:
    containerregistrytype: Azure Container Registry
    azureSubscription: 'Azure-Infra-Terraform'
    azurecontainerregistry: ACR5000
    action: Build an image
    Dockerfile: '**/Dockerfile'
    imageName: :$(Build.Repository.Name):$(Build.BuildId)
 
