# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: DownloadSecureFile@1
  name: certificate
  inputs:
    secureFile: mypoc.crt
- script: |
    mkdir -p  $(DOCKER_CONFIG)/trust/private
    cp $(certificate.secureFilePath)  $(DOCKER_CONFIG)/trust/private
    echo $(DOCKER_CONFIG)/trust/private
    git clone https://github.com/ayushigupta-12/devopsrbapoc

- task: DownloadSecureFile@1
  name: privatekey
  inputs:
    secureFile: mykey.key
- script: |
    cp $(privateKey.secureFilePath)  $(DOCKER_CONFIG)/trust/private
    echo $(DOCKER_CONFIG)/trust/private

- task: Docker@2
  inputs:
    command: build
    Dockerfile: 'dockerfile1'
    containerRegistry: acr-connection
    repository: demopoc
    tags: |
      latest
    arguments: '--disable-content-trust=false'
- script: |
    echo $(System.DefaultWorkingDirectory) 
    cd trust/private
    chmod 600 $(DOCKER_CONFIG)/trust/private/mykey.key
    export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="tcspoc123"
    docker trust key load $(DOCKER_CONFIG)/trust/private/mykey.key --name tcspoc
    az acr login -n acr5000.azurecr.io
    export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE="tcspoc123"
    export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="tcspoc123"
    docker trust signer add --key $(DOCKER_CONFIG)/trust/private/mypoc.crt tcspoc acr5000.azurecr.io/demopoc
   # docker trust signer add --key 15c9270acc563cb0d3ba82299ef3eb6ddfc87ef69dd0558e9cb2dd6d60ada1d8.key poc acr5000.azurecr.io/demopoc

- task: Docker@0
  inputs: 
    containerregistrytype: Azure Container Registry
    azureSubscription: Azure-Infra-Terraform
    azurecontainerRegistry: acr5000
    action: Push an image
    imageName: acr5000.azurecr.io/demopoc:latest
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: tcspoc123
