# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: DownloadSecureFile@1
  name: privateKey
  inputs:
    secureFile: 7cbecf5ebd0b532cd5324fbd92242c36f870a69761ef246c9ad2bce149c29826.key
- script: |
    git clone https://github.com/ayushigupta-12/devopsrbapoc
    mkdir -p $(DOCKER_CONFIG)/trust/private
    cp $(privateKey.secureFilePath) $(DOCKER_CONFIG)/trust/private

- task: Docker@2
  inputs:
    command: build
    Dockerfile: 'dockerfile1'
    containerRegistry: acr-connection
    repository: demopoc
    tags: |
      latest
    arguments: '--disable-content-trust=false'

- task: Docker@0
  inputs: 
    containerregistrytype: Azure Container Registry
    azureSubscription: :Azure-Infra_Pool
    azurecontainerRegistry: acr5000
    action: Push an image
    imageName: acr5000.azurecr.io/dempoc:latest
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: tcspoc123
