# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Download'
    connection: 'sample-rba-art'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "tree/General/libs-snapshots-local/au/gov/rba/rbanet-reservelink/NG.22.11.0.0-SNAPSHOT",
            "target": "$(System.DefaultWorkingDirectory)"
          }
        ]
      }
    failNoOp: true
