# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: DownloadSecureFile@1
  name: certificate
  inputs:
    secureFile: mypoc.crt
- script: |
    mkdir -p $(System.DefaultWorkingDirectory)/trust/private
    cp $(certificate.secureFilePath) $(System.DefaultWorkingDirectory)/trust/private
    echo$(System.DefaultWorkingDirectory)/trust/private
    git clone https://github.com/ayushigupta-12/devopsrbapoc

- task: DownloadSecureFile@1
  name: privatekey
  inputs:
    secureFile: mykey.key
- script: |
    cp $(privateKey.secureFilePath) $(System.DefaultWorkingDirectory)/trust/private
    echo $(System.DefaultWorkingDirectory)/trust/private

- task: Docker@2
  inputs:
    command: build
    Dockerfile: 'dockerfile1'
    containerRegistry: acr-connection
    repository: demopoc2
    tags: |
      latest
    arguments: '--disable-content-trust=false'
- script: |
    echo $(System.DefaultWorkingDirectory)
    cd $(System.DefaultWorkingDirectory)/trust/private
    chmod 600 mykey.key
    sudo export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="tcspoc123"
    sudo docker trust key load mykey.key --name tcspoc
    sudo az acr login -n acr5000.azurecr.io
    sudo export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE="tcspoc123"
    sudo export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="tcspoc123"
    sudo docker trust signer add --key $(System.DefaultWorkingDirectory)/trust/private/mypoc.crt tcspoc acr5000.azurecr.io/demopoc2:latest
    ls
    pwd
    #docker trust key load 042c10894219a41ad36d47dcb95c8e70df49f31d169c02a757eeb9419b02a980.key
    sudo docker trust inspect --pretty acr5000.azurecr.io/demopoc1:latest

- task: Docker@0
  inputs: 
    containerregistrytype: Azure Container Registry
    #azureSubscription: Azure-Infra-Terraform
    azureSubscription: MBU_RBA_NextGen_POC (579ac225-23b7-4453-9785-6042f2570fe8)
    azurecontainerRegistry: acr5000
    action: Push an image
    imageName: acr5000.azurecr.io/demopoc1:latest
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: tcspoc123
