# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

#variables:
  #system.debug: true
  #containerRegistryServiceConnection: serviceConnectionName
  #imageRepository: foobar/content-trust
  #tag: test

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: acr-connection

- task: CmdLine@2
  inputs:
    script: 'echo delegationkey > delegation.key'    

- task: DownloadSecureFile@1
  name: privatekey
  inputs:
    secureFile: mypoc.crt
- script: |
    git clone https://github.com/ayushigupta-12/devopsrbapoc

- task: Docker@2
  inputs:
    command: build
    Dockerfile: 'dockerfile1'
    containerRegistry: acr-connection
    repository: demopoc
    tags: |
      latest
    arguments: '--disable-content-trust=false'
- script: |
    echo $(System.DefaultWorkingDirectory)
    cd trust/private
    docker trust signer add --key mypoc.crt tcspoc acr5000.azurecr.io/demopoc
   # docker trust signer add --key 15c9270acc563cb0d3ba82299ef3eb6ddfc87ef69dd0558e9cb2dd6d60ada1d8.key poc acr5000.azurecr.io/demopoc

- task: Docker@0
  inputs: 
    containerregistrytype: Azure Container Registry
    azureSubscription: Azure-Infra-Terraform
    azurecontainerRegistry: acr5000
    action: Push an image
    imageName: acr5000.azurecr.io/demopoc:latest
  env:
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: tcspoc123
