# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'acr-connection'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'app_acr_registry_service_connection'
    repository: 'mypoc1'
    command: 'build'
    Dockerfile: 'dockerfile1'

- task: Docker@2
  inputs:
    containerRegistry: 'app_acr_registry_service_connection'
    repository: 'mypoc1'
    command: 'push'
    tags: $(Build.BuildId)
- script: |
    docker tag acr5000.azurecr.io/mypoc1:$(Build.BuildId) devopsrbapocjfrog.jfrog.io/dockerimages/mypoc1:$(Build.BuildId)
- task: Docker@2
  inputs:
    containerRegistry: 'jfrogrepo'
    repository: 'dockerimages/mypoc1'
    command: 'push'
    tags: $(Build.BuildId)

- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'artifactorysvc'
    buildName: 'mypoc1'
    buildNumber: $(Build.BuildId)
    allowFailBuild: true





